### ISSUE TITLE
Hosted link

### ISSUE THREAD

**Issue by KendallDoesCoding** [InnateComm/SourceStocks#1]
Is this site hosted on Vercel? Please share the link, if yes.

**Comment by KendallDoesCoding** [comment]
Is this a template taken from Vercel, after reading README, I think it is?

**Comment by suitupstan** [comment]
I've not even started building this project 😅

**Comment by KendallDoesCoding** [comment]
> I've not even started building this project 😅

Oh ok, this is just a template?

**Comment by suitupstan** [comment]
> > I've not even started building this project 😅
> 
> Oh ok, this is just a template?

rn it is just create-next-app. Will push some stuff in a while

**Comment by KendallDoesCoding** [comment]
Ok cool.
